### ISSUE TITLE
怕你看不到 发个新的issues

### ISSUE THREAD

**Issue by anglesgirl** [ZyqGitHub1/h-player-v2#36] opened 2019-08-08 04:06 UTC
https://github.com/magicblack/maccms10/blob/master/%E8%AF%B4%E6%98%8E%E6%96%87%E6%A1%A3/API%E6%8E%A5%E5%8F%A3%E8%AF%B4%E6%98%8E.txt

这是API的官方说明 这是10的版本也是新版本

https://github.com/magicblack/maccms8/blob/master/%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E%E6%96%87%E6%A1%A3/API%E6%8E%A5%E5%8F%A3%E8%AF%B4%E6%98%8E.txt
这是旧版本的API说明 大多数资源站都使用这个版本的API

区别方法就是资源站提供的API连接是
api.php 还是api.php/provide/vod/ 这两个 路径的不同
大多数时候遇到的全部都是老版本

对于多网站资源搜索 我有PHP的演示给你 你可以直接参考一下 源码被加密了 我不知道怎么解密 
对你来说应该不难处理

然后我分享几个我收集的资源站

[
{
    "id": 1,
    "name": "最大",
    "uri": "http://http://www.zuidazy1.net/",
    "httpApi": "http://www.zdziyuan.com/inc/s_api_zuidam3u8.php",
    "httpsApi": "http://www.zdziyuan.com/inc/s_api_zuidam3u8.php",
    "type": "说明"
  },
  {
  "id": 2,
    "name": "酷云",
    "uri": "http://http://www.zuidazy1.net/",
    "httpApi": "http://caiji.kuyun98.com/inc/ldg_kkm3u8.php",
    "httpsApi": "http://caiji.kuyun98.com/inc/ldg_kkm3u8.php",
    "type": "说明"
  },
  {
  "id": 3,
    "name": "秒播",
    "uri": "http://http://www.zuidazy1.net/",
    "httpApi": "https://www.miaobozy.com/api.php/provide/vod/from/miaom3u8/at/xml/",
    "httpsApi": "https://www.miaobozy.com/api.php/provide/vod/from/miaom3u8/at/xml/",
    "type": "说明"
  },
 {
    "id": 8,
    "name": "ok",
    "uri": "https://wolongzy.net/",
    "httpApi": "https://cj.okzy.tv/inc/apickm3u8s.php",
    "httpsApi": "https://cj.okzy.tv/inc/apickm3u8s.php",
    "type": "说明"
  },
  {
    "id": 9,
    "name": "卧龙",
    "uri": "https://wolongzy.net/",
    "httpApi": "https://cj.wlzy.tv/inc/s_api_mac_m3u8.php",
    "httpsApi": "https://cj.wlzy.tv/inc/s_api_mac_m3u8.php",
    "type": "说明"
  },
   {
    "id": 10,
    "name": "速播",
    "uri": "https://www.subo8988.com",
    "httpApi": "https://www.subo8988.com/inc/maccms_subom3u8.php",
    "httpsApi": "https://www.subo8988.com/inc/maccms_subom3u8.php",
    "type": "说明"
  },
  {
    "id": 11,
    "name": "哈酷",
    "uri": "https://api.haku77.com",
    "httpApi": "https://api.haku77.com/inc/hkm3u8.php",
    "httpsApi": "https://api.haku77.com/inc/hkm3u8.php",
    "type": "顶部跑马灯水印"
  },
    {
    "id": 12,
    "name": "172",
    "uri": "http://www.172zyw.net/inc/172m3u8.php",
    "httpApi": "http://www.172zyw.net/inc/172m3u8.php",
    "httpsApi": "http://www.172zyw.net/inc/172m3u8.php",
    "type": "顶部跑马灯水印"
  },
    {
    "id": 13,
    "name": "豆瓣云",
    "uri": "http://www.dbzyz.com/inc/dbm3u8.php",
    "httpApi": "http://www.dbzyz.com/inc/dbm3u8.php",
    "httpsApi": "http://www.dbzyz.com/inc/dbm3u8.php",
    "type": "顶部跑马灯水印"
  },
      {
    "id": 14,
    "name": "八戒",
    "uri": "http://zy.bajieziyuan.com/inc/bjm3u8.php",
    "httpApi": "http://zy.bajieziyuan.com/inc/bjm3u8.php",
    "httpsApi": "http://zy.bajieziyuan.com/inc/bjm3u8.php",
    "type": "顶部跑马灯水印"
	}
]

**Comment by ZyqGitHub1** [comment] 2019-08-08 16:11
Thank you very much for your help. These documents are very useful and I will use them as a reference in development and maintenance.
The video source files I provide are just examples. You can create and maintain your own video source files and share them with other users. Maintaining the video source files is not in my regular development plan.
As for multi-site resource search, this is more than just calling api, I need to design additional search pages and interactions.

------

十分感谢你提供的帮助，这些文档很有用，我会在开发维护中作为参考。
我提供的视频源文件仅仅是示例，你可以创建和维护自己的视频源文件，并分享给其他用户，维护视频源文件不在我的常规开发计划之中。
至于多网站资源搜索，这不仅仅是调用api，我需要额外设计搜索页面和交互。

**Comment by ZyqGitHub1** [comment] 2019-08-13 07:50
Duplicate of #29

**Closed by ZyqGitHub1** 2019-08-13 07:50 UTC
